{{- range $name, $secrets := $.Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ tpl $name $ }}
  namespace: {{ $.Release.Namespace }}
  annotations: 
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    {{- range $secret_name, $secret_value := $secrets }}
    {{ $secret_name }}: {{ $secret_value }}
    {{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ tpl $name $ }}
      namespace: {{ $.Release.Namespace }}
    type: Opaque
---
{{- end }}