{{ if has "guacamole" .Values.components }}
# Guacd service
apiVersion: v1
kind: Service
metadata:
  name: guacd-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
  selector:
    app: guacd
---
# Guacd deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      restartPolicy: Always
      containers:
        - name: guacd-container
          image: guacamole/guacd
          imagePullPolicy: Always
          ports:
            - containerPort: 4822
          volumeMounts:
            - name: guac-shared-volume
              mountPath: "/shared/"
          startupProbe:
            tcpSocket:
              port: 4822
            failureThreshold: 45
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 0
            periodSeconds: 1
      volumes:
        - name: guac-shared-volume
          emptyDir: {}
---
# Guacamole properties configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-properties-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  guacamole.properties: |
{{ tpl .Values.guacamole.properties . | indent 4 }}
---
{{ if .Values.guacamole.debug }}
# Guacamole logback.xml for more details in the logs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-logback-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  logback.xml: |
    <configuration>

        <!-- Appender for debugging -->
        <appender name="GUAC-DEBUG" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <!-- Log at DEBUG level -->
        <root level="debug">
            <appender-ref ref="GUAC-DEBUG"/>
        </root>

    </configuration>
---
{{ end }}
# Guacamole service
apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: guacamole
---
# Guacamole deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      restartPolicy: Always
      initContainers:
        - name: guacamole-init-container
          image: alphabet5/guacamole
          command:
            - '/bin/bash'
            - '-c'
            - 'cp /extensions/guacamole-auth-ldap*.jar /emptydir/'
          volumeMounts:
            - name: guac-extensions-volume
              mountPath: "/emptydir/"
      containers:
        - name: guacamole-container
          image: guacamole/guacamole:{{ .Values.guacamole.version }}
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
            - >
              sed -i 's#      </Host>#        <Valve className="org.apache.catalina.valves.RemoteIpValve"\n               internalProxies=".*"\n               remoteIpHeader="x-forwarded-for"\n               remoteIpProxiesHeader="x-forwarded-by"\n               protocolHeader="x-forwarded-proto" />\n      </Host>#' /usr/local/tomcat/conf/server.xml; mkdir /etc/guacamole; mkdir /etc/guacamole/extensions; cp /opt/guacamole/ldap/guacamole-auth-ldap-*.jar /etc/guacamole/extensions; exec /opt/guacamole/bin/start.sh
          env:
            - name: MYSQL_USER
              value: {{ .Values.mysql.mysql_username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.mysql_database }}
            - name: GUACD_HOSTNAME
              value: guacd-service
            - name: MYSQL_HOSTNAME
              value: guac-mysql-service
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
            - name: LDAP_SEARCH_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: ldap_password
          ports:
            - name: guacamole
              containerPort: 8080
          volumeMounts:
            - name: guacamole-properties-volume
              mountPath: "/etc/guacamole/guacamole.properties"
              subPath: "guacamole.properties"
            {{- if .Values.guacamole.debug }}
            - name: guacamole-logback-volume
              mountPath: "/etc/guacamole/logback.xml"
              subPath: "logback.xml"
            {{- end }}
            - name: guac-extensions-volume
              mountPath: "/etc/guacamole/extensions/"
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 45
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
      volumes:
        - name: guacamole-properties-volume
          configMap:
            name: guacamole-properties-configmap
        {{- if .Values.guacamole.debug }}
        - name: guacamole-logback-volume
          configMap:
            name: guacamole-logback-configmap
        {{- end }}
        - name: guac-extensions-volume
          emptyDir: {}
{{ end }}