{{ if has "guacamole_users" .Values.components }}
# Guacamole users configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-users-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  {{- if hasKey .Values.guacamole_users "manual_connections" }}
  manual-connections.yaml: |
{{ tpl .Values.guacamole_users.manual_connections . | indent 4 }}
  {{- end }}
  {{- if hasKey .Values.guacamole_users "auto_connections" }}
  auto-connections.yaml: |
{{ tpl .Values.guacamole_users.auto_connections . | indent 4 }}
  {{- end }}
---
# Guacamole users deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-users-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-users
  template:
    metadata:
      labels:
        app: guacamole-users
    spec:
      restartPolicy: Always
      containers:
        - name: guacamole-users-container
          image: alphabet5/guacamole-users:{{ .Values.guacamole_users.version }}
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: {{ .Values.guacamole_users.debug | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.mysql_username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.mysql_database | quote }}
            - name: MYSQL_HOSTNAME
              value: guac-mysql-service
            - name: LDAP_SEARCH_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: ldap_password
            - name: CFG_AUTO_CONNECTION_DNS
              value: {{ .Values.guacamole_users.auto_connection_dns | quote }}
            - name: CFG_AUTO_CONNECTION_DNS_RESOLVER
              value: {{ .Values.guacamole_users.auto_connection_dns_resolver | quote }}
            - name: GUAC_ADMIN_GROUPS
              value: {{ .Values.guacamole_users.guac_admin_groups | quote }}
            - name: LDAP_BASE_DN
              value: {{ tpl .Values.guacamole_users.ldap_base_dn . | quote }}
            - name: LDAP_COMPUTER_FILTER
              value: {{ .Values.guacamole_users.ldap_computer_filter | quote }}
            - name: LDAP_GROUP_NAME_FROM_CONN_NAME_REGEX
              value: {{ .Values.guacamole_users.ldap_group_name_from_conn_name_regex | quote }}
            - name: LDAP_GROUP_NAME_MOD
              value: {{ .Values.guacamole_users.ldap_group_name_mod | quote }}
            - name: REFRESH_SPEED
              value: {{ .Values.guacamole_users.refresh_speed | quote }}
            - name: MANUAL_ONLY
              value: {{ .Values.guacamole_users.manual_only | quote }}
          volumeMounts:
          {{- if hasKey .Values.guacamole_users "manual_connections" }}
            - name: guacamole-users-volume
              mountPath: "/configs/manual-connections.yaml"
              subPath: "manual-connections.yaml"
          {{- end }}
          {{- if hasKey .Values.guacamole_users "auto_connections" }}
            - name: guacamole-users-volume
              mountPath: "/configs/auto-connections.yaml"
              subPath: "auto-connections.yaml"
          {{- end }}
            - name: guacamole-properties-volume
              mountPath: "/configs/guacamole.properties"
              subPath: "guacamole.properties"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: guacamole-users-volume
          configMap:
            name: guacamole-users-configmap
        - name: guacamole-properties-volume
          configMap:
            name: guacamole-properties-configmap
{{ end }}