{{ if has "dnsmasq" .Values.components }}
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service-tcp
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  annotations:
    metallb.universe.tf/allow-shared-ip: global
  {{- end }}
spec:
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.kubernetes.metallb_ip }}
  {{- end }}
  {{- if eq .Values.kubernetes.networking "NodePort" }}
  type: NodePort
  {{- end }}
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
      {{- if eq .Values.kubernetes.networking "NodePort" }}
      nodePort: 53
      {{- end }}
  selector:
    app: dnsmasq
---
apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service-udp
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  annotations:
    metallb.universe.tf/allow-shared-ip: global
  {{- end }}
spec:
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.kubernetes.metallb_ip }}
  {{- end }}
  {{- if eq .Values.kubernetes.networking "NodePort" }}
  type: NodePort
  {{- end }}
  ports:
    - name: dnstcp
      protocol: UDP
      port: 53
      targetPort: 53
      {{- if eq .Values.kubernetes.networking "NodePort" }}
      nodePort: 53
      {{- end }}
  selector:
    app: dnsmasq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq-container
          image: alphabet5/dnsmasq:{{ .Values.dnsmasq.version }}
          imagePullPolicy: Always
          args:
            {{- range .Values.dnsmasq.args }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 20
{{ end }}