{{ if has "smtp" .Values.components }}
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay-service
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  annotations:
    metallb.universe.tf/allow-shared-ip: global
  {{- end }}
spec:
  {{- if eq .Values.kubernetes.networking "MetalLB" }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.kubernetes.metallb_ip.shared }}
  {{- end }}
  {{- if eq .Values.kubernetes.networking "NodePort" }}
  type: NodePort
  {{- end }}
  ports: 
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
  selector:
    app: smtp-relay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-relay-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-relay
  template:
    metadata:
      labels:
        app: smtp-relay
    spec:
      containers:
        - name: smtp-relay-container
          image: namshi/smtp:{{ .Values.smtp.version }}
          imagePullPolicy: Always
          env:
            {{- if eq .Values.smtp.type "gmail" }}
            - name: GMAIL_USER
              value: {{ .Values.smtp.gmail_user | quote }}
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-relay
                  key: password
            - name: RELAY_NETWORKS
              value: {{ .Values.smtp.relay_networks | quote }}
            {{- end }}
            {{- if eq .Values.smtp.type "smarthost" }}
            - name: SMARTHOST_ADDRESS
              value: {{ .Values.smtp.smarthost_address | quote }}
            - name: SMARTHOST_PORT
              value: {{ .Values.smtp.smarthost_port | quote }}
            - name: RELAY_NETWORKS
              value: {{ .Values.smtp.relay_networks | quote }}
            - name: SMARTHOST_USER
              value: {{ .Values.smtp.smarthost_user | quote }}
            - name: SMARTHOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-relay
                  key: password
            {{- end }}
          ports:
            - containerPort: 25
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 25
            failureThreshold: 30
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 0
            periodSeconds: 1
{{ end }}