{{- if .Values.authelia.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-authelia" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Method $request_method;
    # nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-name: {{ printf "%s-guacamole" .Release.Name }}
    # nginx.ingress.kubernetes.io/affinity-mode: persistent
    # nginx.ingress.kubernetes.io/session-cookie-samesite: Strict
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "36000"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "36000"
    # nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    {{- if eq .Values.certManager.kind "ClusterIssuer" }}
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ printf "%s-cert-manager" .Release.Name }}
    {{- else }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.name | quote }}
    {{- end }}
    {{- else if eq .Values.certManager.kind "Issuer" }}
    {{- if .Values.certManager.enabled }}
    cert-manager.io/issuer: {{ printf "%s-cert-manager" .Release.Name }}
    {{- else }}
    cert-manager.io/issuer: {{ .Values.certManager.name | quote }}
    {{- end }}
    {{- end }}
spec:
  rules:
    - host: {{ tpl .Values.authelia.dnsName . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-authelia" .Release.Name }}
                port:
                  number: 9091
  tls:
    - hosts:
      - {{ tpl .Values.authelia.dnsName . }}
      secretName: {{ printf "%s-authelia-tls" .Release.Name }}
{{- end }}
