{{- if .Values.authelia.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-authelia" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: authelia
  sessionAffinity: "ClientIP"
  internalTrafficPolicy: Local
{{- end }}
