{{ if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-cert-manager" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.acmeServer }}
    {{- if ne .Values.certManager.acmeExternalAccountKeyId "" }}
    externalAccountBinding:
      keyID: {{ .Values.certManager.acmeExternalAccountKeyId }}
      keySecretRef:
        name: {{ printf "%s-cert-manager-external-account-key" .Release.Name }}
        key: acme_external_account_key
      keyAlgorithm: HS256
    {{- end }}
    privateKeySecretRef:
      name: {{ printf "%s-acme-private-key" .Release.Name }}
    solvers:
      - selector: {}
        dns01:
          route53:
            region: {{ .Values.certManager.route53Region }}
            accessKeyID: {{ .Values.certManager.route53AccessKeyId }}
            secretAccessKeySecretRef:
              name: {{ printf "%s-cert-manager-route53-key" .Release.Name }}
              key: secret_access_key
            {{- if ne .Values.certManager.route53HostedZoneId "" }}
            hostedZoneID: {{ .Values.certManager.route53HostedZoneId }}
            {{- end }}
{{- end }}
