{{- if .Values.dnsmasq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-dnsmasq-udp" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    metallb.universe.tf/allow-shared-ip: global
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.dnsmasq.loadBalancerIpAddress }}
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: dnsmasq
{{- end }}