{{- if .Values.duo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-duo-auth-proxy" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.duo.replicas }}
  selector:
    matchLabels:
      app: duo-auth-proxy
  template:
    metadata:
      labels:
        app: duo-auth-proxy
    spec:
      containers:
        - name: {{ printf "%s-duo-auth-proxy" .Release.Name }}
          image: alphabet5/duoauthproxy:{{ .Values.duo.version }}
          imagePullPolicy: Always
          env:
            - name: DUO_AD_HOST
              value: {{ tpl .Values.duo.duoAdHost . | quote }}
            - name: DUO_AD_USER
              value: {{ tpl .Values.duo.duoAdUser . | quote }}
            - name: DUO_AD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-duo" .Release.Name }}
                  key: duo_ad_password
            - name: DUO_AD_SEARCH_DN
              value: {{ tpl .Values.duo.duoAdSeachDn . | quote}}
            - name: DUO_INTEGRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-duo" .Release.Name }}
                  key: duo_integration_key
            - name: DUO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-duo" .Release.Name }}
                  key: duo_secret_key
            - name: DUO_API_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-duo" .Release.Name }}
                  key: duo_api_hostname
            - name: DUO_RADIUS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-duo" .Release.Name }}
                  key: duo_radius_secret
            - name: DUO_FAILMODE
              value: {{ .Values.duo.duo_failmode }}
            - name: DUO_PORT
              value: "1812"
          ports:
            - containerPort: 1812
              protocol: UDP
{{- end }}