{{- if .Values.duo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-duo-auth-proxy" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.duo.sharedIp }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ tpl .Values.duo.loadBalancerIpAddress . }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ tpl .Values.duo.loadBalancerIpAddress . }}
  ports:
    - name: radius
      protocol: UDP
      port: 1812
      targetPort: 1812
  selector:
    app: duo-auth-proxy
{{- end }}
