{{- if .Values.guacamole.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-guacd" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.guacamole.replicas }}
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      restartPolicy: Always
      containers:
        - name: {{ printf "%s-guacd" .Release.Name }}
          image: guacamole/guacd:{{ .Values.guacamole.guacdVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4822
          volumeMounts:
            - name: {{ printf "%s-guacd-shared-volume" .Release.Name }}
              mountPath: "/shared/"
          startupProbe:
            tcpSocket:
              port: 4822
            failureThreshold: 45
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 1
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 1
            periodSeconds: 1
      volumes:
        - name: {{ printf "%s-guacd-shared-volume" .Release.Name }}
          emptyDir: {}
{{- end }}