{{- if and .Values.guacamole.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-guacamole" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: guacamole
{{- end }}
