{{- if .Values.guacamole.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-guacamole" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: {{ .Values.guacamole.dnsName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-guacamole" .Release.Name }}
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.guacamole.dnsName }}
    secretName: {{ printf "%s-guacamole-tls" .Release.Name }}
{{- end }}