{{- if and .Values.guacamole.enabled .Values.certManager.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-guacamole" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "public"
    nginx.ingress.kubernetes.io/app-root: "/guacamole/"
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    cert-manager.io/issuer: {{ printf "%s-letsencrypt" .Release.Name }}
spec:
  rules:
    - host: {{ .Values.guacamole.dnsName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-guacamole" .Release.Name }}
                port:
                  number: 8080
  tls:
    - hosts:
      - {{ .Values.guacamole.dnsName }}
      secretName: {{ printf "%s-guacamole-tls" .Release.Name }}
{{- end }}
