{{- if Values.guacamole.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { printf "%s-guacamole" .Release.Name } }
  namespace: { { .Release.Namespace | quote } }
spec:
  replicas: {{ Values.guacamole.replicas }}
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      restartPolicy: Always
      initContainers:
        - name: {{ printf "%s-guacamole-init" .Release.Name }}
          image: alphabet5/guacamole
          command:
            - '/bin/bash'
            - '-c'
            - 'cp /extensions/guacamole-auth-ldap*.jar /emptydir/'
          volumeMounts:
            - name: {{ printf "%s-guacamole-extensions-volume" .Release.Name }}
              mountPath: "/emptydir/"
      containers:
        - name: {{ printf "%s-guacamole" .Release.Name }}
          image: guacamole/guacamole:{{ .Values.guacamole.version }}
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
            - >
              sed -i 's#      </Host>#        <Valve className="org.apache.catalina.valves.RemoteIpValve"\n               internalProxies=".*"\n               remoteIpHeader="x-forwarded-for"\n               remoteIpProxiesHeader="x-forwarded-by"\n               protocolHeader="x-forwarded-proto" />\n      </Host>#' /usr/local/tomcat/conf/server.xml; mkdir /etc/guacamole; mkdir /etc/guacamole/extensions; cp /opt/guacamole/ldap/guacamole-auth-ldap-*.jar /etc/guacamole/extensions; exec /opt/guacamole/bin/start.sh
          env:
            - name: MYSQL_USER
              value: {{ .Values.mysql.mysql_username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.mysql_database }}
            - name: GUACD_HOSTNAME
              value: guacd-service
            - name: MYSQL_HOSTNAME
              value: guac-mysql-service
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
            - name: LDAP_SEARCH_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-secret
                  key: ldap_password
          ports:
            - name: guacamole
              containerPort: 8080
          volumeMounts:
            - name: guacamole-properties-volume
              mountPath: "/etc/guacamole/guacamole.properties"
              subPath: "guacamole.properties"
            {{- if .Values.guacamole.debug }}
            - name: guacamole-logback-volume
              mountPath: "/etc/guacamole/logback.xml"
              subPath: "logback.xml"
            {{- end }}
            - name: guac-extensions-volume
              mountPath: "/etc/guacamole/extensions/"
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 45
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
      volumes:
        - name: guacamole-properties-volume
          configMap:
            name: guacamole-properties-configmap
        {{- if .Values.guacamole.debug }}
        - name: guacamole-logback-volume
          configMap:
            name: guacamole-logback-configmap
        {{- end }}
        - name: {{ printf "%s-guacamole-extensions-volume" .Release.Name }}
          emptyDir: {}
{{- end }}