{{- if and .Values.guacamole.enabled .Values.guacamole.users.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-guacamole-users" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.guacamole.users.replicas }}
  selector:
    matchLabels:
      app: guacamole-users
  template:
    metadata:
      labels:
        app: guacamole-users
    spec:
      restartPolicy: Always
      containers:
        - name: {{ printf "%s-guacamole-users" .Release.Name }}
          image: alphabet5/guacamole-users:{{ .Values.guacamole.users.version }}
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: {{ .Values.guacamole.users.debug | quote }}
            - name: MYSQL_USER
              value: {{ .Values.guacamole.sql.mysqlUser | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: mysql_password
            - name: MYSQL_DATABASE
              value: {{ .Values.gaucamole.sql.usersDatabase | quote }}
            - name: MYSQL_HOSTNAME
              value: {{ printf "%s-mysql" .Release.Name }}
            - name: LDAP_SEARCH_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: ldap_bind_password
            - name: CFG_AUTO_CONNECTION_DNS
              value: {{ .Values.guacamole.users.autoConnectionDns | quote }}
            - name: CFG_AUTO_CONNECTION_DNS_RESOLVER
              value: {{ .Values.guacamole.users.autoConnectionDnsResolver | quote }}
            - name: GUAC_ADMIN_GROUPS
              value: {{ .Values.guacamole.users.guacAdminGroup | quote }}
            - name: LDAP_BASE_DN
              value: {{ tpl .Values.guacamole_users.ldap_base_dn . | quote }}
            - name: LDAP_COMPUTER_FILTER
              value: {{ .Values.guacamole_users.ldap_computer_filter | quote }}
            - name: LDAP_GROUP_NAME_FROM_CONN_NAME_REGEX
              value: {{ .Values.guacamole_users.ldap_group_name_from_conn_name_regex | quote }}
            - name: LDAP_GROUP_NAME_MOD
              value: {{ .Values.guacamole_users.ldap_group_name_mod | quote }}
            - name: REFRESH_SPEED
              value: {{ .Values.guacamole_users.refresh_speed | quote }}
            - name: MANUAL_ONLY
              value: {{ .Values.guacamole_users.manual_only | quote }}
          volumeMounts:
          {{- if hasKey .Values.guacamole_users "manual_connections" }}
            - name: guacamole-users-volume
              mountPath: "/configs/manual-connections.yaml"
              subPath: "manual-connections.yaml"
          {{- end }}
          {{- if hasKey .Values.guacamole_users "auto_connections" }}
            - name: guacamole-users-volume
              mountPath: "/configs/auto-connections.yaml"
              subPath: "auto-connections.yaml"
          {{- end }}
            - name: guacamole-properties-volume
              mountPath: "/configs/guacamole.properties"
              subPath: "guacamole.properties"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: guacamole-users-volume
          configMap:
            name: guacamole-users-configmap
        - name: guacamole-properties-volume
          configMap:
            name: guacamole-properties-configmap
{{- end }}