{{- if and .Values.guacamole.enabled .Values.guacamole.users.enabled .Values.certManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-guacamole-users" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.guacamole.users.replicas }}
  selector:
    matchLabels:
      app: guacamole-users
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/guacamole-users-configmap.yaml") . | sha256sum }}
        checksum/properties: {{ include (print $.Template.BasePath "/guacamole-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/guacamole-secret.yaml") . | sha256sum }}
      labels:
        app: guacamole-users
    spec:
      restartPolicy: {{ .Values.guacamole.users.restartPolicy | quote }}
      containers:
        - name: {{ printf "%s-guacamole-users" .Release.Name }}
          image: {{ .Values.guacamole.users.image }}
          imagePullPolicy: {{ .Values.guacamole.users.imagePullPolicy | quote }}
          env:
            - name: DEBUG
              value: {{ .Values.guacamole.users.debug | quote }}
            - name: MYSQL_HOSTNAME
              value: {{ printf "%s-mysql" .Release.Name }}
            - name: MYSQL_DATABASE
              value: {{ .Values.guacamole.sql.usersDatabase | quote }}
            - name: MYSQL_USER
              value: {{ .Values.guacamole.sql.mysqlUser | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: mysql_password
            - name: CFG_AUTO_CONNECTION_DNS
              value: {{ .Values.guacamole.users.autoConnectionDns | quote }}
            - name: CFG_AUTO_CONNECTION_DNS_RESOLVER
              value: {{ .Values.guacamole.users.autoConnectionDnsResolver | quote }}
            - name: GUAC_ADMIN_GROUPS
              value: {{ .Values.guacamole.users.guacAdminGroups | quote }}
            - name: LDAP_BASE_DN
              value: {{ tpl .Values.guacamole.users.ldapBaseDn . | quote }}
            - name: LDAP_COMPUTER_FILTER
              value: {{ .Values.guacamole.users.ldapComputerFilter | quote }}
            - name: LDAP_GROUP_NAME_FROM_CONN_NAME_REGEX
              value: {{ .Values.guacamole.users.ldapGroupNameFromConnNameRegex | quote }}
            - name: LDAP_GROUP_NAME_MOD
              value: {{ .Values.guacamole.users.ldapGroupNameMod | quote }}
            - name: LDAP_SEARCH_BIND_DN
              value: {{ tpl .Values.guacamole.ldapBindUser . | quote}}
            - name: LDAP_SEARCH_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: ldap_bind_password
            - name: REFRESH_SPEED
              value: {{ .Values.guacamole.users.refreshSpeed | quote }}
            - name: MANUAL_ONLY
              value: {{ .Values.guacamole.users.manualOnly | quote }}
          volumeMounts:
          {{- if .Values.guacamole.users.manualConnections }}
            - name: {{ printf "%s-guacamole-users-volume" .Release.Name }}
              mountPath: "/configs/manual-connections.yaml"
              subPath: "manual-connections.yaml"
          {{- end }}
          {{- if .Values.guacamole.users.autoConnections }}
            - name: {{ printf "%s-guacamole-users-volume" .Release.Name }}
              mountPath: "/configs/auto-connections.yaml"
              subPath: "auto-connections.yaml"
          {{- end }}
            - name: {{ printf "%s-guacamole-properties-volume" .Release.Name }}
              mountPath: "/configs/guacamole.properties"
              subPath: "guacamole.properties"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: {{ printf "%s-guacamole-users-volume" .Release.Name }}
          configMap:
            name: {{ printf "%s-guacamole-users" .Release.Name }}
        - name: {{ printf "%s-guacamole-properties-volume" .Release.Name }}
          configMap:
            name: {{ printf "%s-guacamole" .Release.Name }}
            items:
            - key: guacamole.properties
              path: guacamole.properties
{{- end }}
