apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy-container
          image: haproxy:{{ .Values.haproxy.version }}
          imagePullPolicy: Always
          ports:
            {{- range .Values.haproxy.ports }}
            - containerPort: {{ .targetPort }}
            {{- end }}
          volumeMounts:
            - name: haproxy-volume
              mountPath: "/usr/local/etc/haproxy/haproxy.cfg"
              subPath: "haproxy.cfg"
            - name: haproxy-certs-volume
              mountPath: "/usr/local/etc/certs/"
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 1
      volumes:
        - name: haproxy-volume
          configMap:
            name: haproxy-configmap
        - name: haproxy-certs-volume
          secret:
            secretName: haproxy-app-tls
{{ end }}