{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ingress" .Release.Name }}
  namespace: ingress
  {{- if .Values.ingress.sharedIp }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Values.ingress.loadBalancerIpAddress }} 
  {{- end }}
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ingress.loadBalancerIpAddress }}
{{- end }}
