apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ingress" .Release.Name }}
  namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: {{ .Values.ingress.loadBalancerIpAddress }}