{{- if and .Values.guacamole.enabled .Values.guacamole.sql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-mysql" .Release.Name }}
  namespace: {{ .Release.Namespace | quote}}
spec:
  replicas: {{ .Values.guacamole.sql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      initContainers:
        - name: {{ printf "%s-mysql-init" .Release.Name }}
          image: guacamole/guacamole:{{ .Values.guacamole.version }}
          command:
            - '/bin/bash'
            - '-c'
            - '/opt/guacamole/bin/initdb.sh --mysql > /mysqlinit/initdb.sql'
          volumeMounts:
            - name: {{ printf "%s-mysql-guac-init-volume" .Release.Name }}
              mountPath: "/mysqlinit/"
      containers:
        - name: {{ printf "%s-mysql" .Release.Name }}
          image: {{ .Values.gaucamole.sql.image }}:{{ .Values.guacamole.sql.version }}
          imagePullPolicy: Always
          env:
            - name: MYSQL_USER
              value: {{ .Values.guacamole.sql.mysqlUser }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: mysql_password
            - name: MYSQL_DATABASE
              value: {{ .Values.guacamole.sql.usersDatabase }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: mysql_root_password
            - name: GUACADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-guacamole" .Release.Name }}
                  key: guac_admin_password
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: {{ printf "%s-mysql-guac-init-volume" .Release.Name }}
              mountPath: "/mysqlinit/"
            - name: {{ printf "%s-mysql-init-volume" .Release.Name }}
              mountPath: "/docker-entrypoint-initdb.d/initdb.sh"
              subPath: "initdb.sh"
            - name: {{ printf "%s-mysql-volume" .Release.Name }}
              mountPath: "/var/lib/mysql/"
          startupProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
                - '-h'
                - 'localhost'
            failureThreshold: 60
            periodSeconds: 1
          readinessProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
                - '-h'
                - 'localhost'
            initialDelaySeconds: 0
            periodSeconds: 1
          livenessProbe:
            exec:
              command:
                - 'mysqladmin'
                - 'ping'
                - '-h'
                - 'localhost'
            initialDelaySeconds: 0
            periodSeconds: 1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: { { printf "%s-mysql-guac-init-volume" .Release.Name } }
          emptyDir: { }
        - name: {{ printf "%s-mysql-init-volume" .Release.Name }}
          configMap:
            name: {{ printf "%s-mysql" .Release.Name }}
        - name: {{ printf "%s-mysql-volume" .Release.Name }}
          emptyDir: {}
{{- end }}