{{- if and .Values.guacamole.enabled .Values.guacamole.sql.enabled .Values.certManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-mysql" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
{{- end }}
