{{- if and .Values.rdpgw.enabled .Values.certManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rdpgw-authelia" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.rdpgw.authelia.replicas }}
  selector:
    matchLabels:
      app: rdpgw-authelia
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/rdpgw-authelia-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/rdpgw-secret.yaml") . | sha256sum }}
      labels:
        app: rdpgw-authelia
    spec:
      restartPolicy: {{ .Values.rdpgw.authelia.restartPolicy  | quote }}
      initContainers:
        - name: {{ printf "%s-authelia-init" .Release.Name }}
          image: {{ .Values.rdpgw.authelia.image }}
          imagePullPolicy: {{ .Values.rdpgw.authelia.imagePullPolicy | quote }}
          env:
            - name: RDPGW_OPEN_ID__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-rdpgw" .Release.Name }}
                  key: rdpgw_open_id__client_secret
            - name: RDPGW_OPEN_ID_DNS_NAME
              value: {{ tpl .Values.rdpgw.dnsName . }}
          command:
            - 'sh'
            - '-c'
            - 'sed -e "s:\$RDPGW_OPEN_ID__CLIENT_SECRET:${RDPGW_OPEN_ID__CLIENT_SECRET}:g" -e "s:\$RDPGW_OPEN_ID_DNS_NAME:${RDPGW_OPEN_ID_DNS_NAME}:g" /configuration.yml > /config/configuration.yml'
          volumeMounts:
            - name: {{ printf "%s-rdpgw-authelia-configmap-volume" .Release.Name }}
              mountPath: /configuration.yml
              subPath: configuration.yml
            - name: {{ printf "%s-rdpgw-authelia-emptydir-volume" .Release.Name }}
              mountPath: "/config/"
      containers:
        - name: {{ printf "%s-rdpgw-authelia" .Release.Name }}
          image: {{ .Values.rdpgw.authelia.image }}
          imagePullPolicy: {{ .Values.rdpgw.authelia.imagePullPolicy  | quote }}
          env:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /app/secrets/jwt
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /app/secrets/storage
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
              value: /app/secrets/ldap
            - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
              value: /app/secrets/issuer
            - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
              value: /app/secrets/hmac
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER
              value: {{ tpl .Values.rdpgw.authelia.ldapUser . }}
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_URL
              value: {{ tpl .Values.rdpgw.authelia.ldapUrl . }}
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN
              value: {{ tpl .Values.rdpgw.authelia.ldapBaseDn . }}
          ports:
            - name: authelia
              containerPort: 9091
          volumeMounts:
            - name: {{ printf "%s-rdpgw-authelia-secrets-volume" .Release.Name }}
              mountPath: /app/secrets
              readOnly: true
            - name: {{ printf "%s-rdpgw-authelia-emptydir-volume" .Release.Name }}
              mountPath: "/config/"
          startupProbe:
            httpGet:
              path: /api/state
              port: 9091
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /api/state
              port: 9091
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /api/state
              port: 9091
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
      volumes:
        - name: {{ printf "%s-rdpgw-authelia-configmap-volume" .Release.Name }}
          configMap:
            name: {{ printf "%s-rdpgw-authelia" .Release.Name }}
            items:
            - key: configuration.yml
              path: configuration.yml
        - name: {{ printf "%s-rdpgw-authelia-emptydir-volume" .Release.Name }}
          emptyDir: {}
        - name: {{ printf "%s-rdpgw-authelia-secrets-volume" .Release.Name }}
          secret:
            secretName: {{ printf "%s-rdpgw" .Release.Name }}
            items:
              - key: authelia_jwt_secret_file
                path: jwt
              - key: authelia_storage_encryption_key_file
                path: storage
              - key: authelia_authentication_backend_ldap_password_file
                path: ldap
              - key: authelia_identity_providers_oidc_issuer_private_key_file
                path: issuer
              - key: authelia_identity_providers_oidc_hmac_secret_file
                path: hmac
{{- end }}
