{{- if and .Values.guacamole.enabled .Values.certManager.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ printf "%s-rdpgw" .Release.Name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    rdpgw_server__session_key: {{ .Values.rdpgw.secrets.serverSessionKey }}
    rdpgw_server__session_encryption_key: {{ .Values.rdpgw.secrets.serverSessionEncryptionKey }}
    rdpgw_open_id__client_secret: {{ .Values.rdpgw.secrets.openIdClientSecret }}
    rdpgw_security__paa_token_signing_key: {{ .Values.rdpgw.secrets.securityPaaTokenSigningKey }}
    rdpgw_security__paa_token_encryption_key: {{ .Values.rdpgw.secrets.SecurityPaaTokenEncryptionKey }}
    {{- if .Values.rdpgw.authelia.enabled }}
    authelia_jwt_secret_file: {{ .Values.rdpgw.authelia.secrets.jwtSecret }}
    authelia_storage_encryption_key_file: {{ .Values.rdpgw.authelia.secrets.storageEncryptionKey }}
    authelia_authentication_backend_ldap_password_file: {{ .Values.rdpgw.authelia.secrets.backendLdapPassword }}
    authelia_identity_providers_oidc_issuer_private_key_file: {{ .Values.rdpgw.authelia.secrets.issuer }}
    authelia_identity_providers_oidc_hmac_secret_file: {{ .Values.rdpgw.authelia.secrets.hmac }}
    {{- end }}
  template:
    type: Opaque
{{- end }}
