{{- if .Values.smtp.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ printf "%s-smtp" .Release.Name }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    {{- if .Values.smtp.secrets.nextHopPassword }}
    next_hop_password: {{ .Values.smtp.secrets.nextHopPassword }}
    {{- end }}
  template:
    type: Opaque
{{- end }}
