{{ if .Values.squid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-squid" .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.squid.sharedIp }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ tpl .Values.squid.loadBalancerIpAddress . }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ tpl .Values.squid.loadBalancerIpAddress . }}
  {{- if not .Values.squid.sharedIp }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - name: proxy
      protocol: TCP
      port: {{ .Values.squid.squidPort }}
      targetPort: 3128
  selector:
    app: squid
{{- end }}
