guacamole:
  enabled: true
  version: 1.4.0
  guacdVersion: latest
  debug: false
  replicas: 1
  guacdPort: 4822
  guacamolePort: 8080
  sharedVolumeSize: 2G
  properties: |
  	enable-environment-properties: true
    ldap-encryption-method: none
    ldap-group-base-dn: {{ .Values.global.default_domain_ldap }}
    ldap-group-search-filter: (objectCategory=group)
    ldap-group-name-attribute: cn
    ldap-hostname: {{ .Values.global.default_domain }}
    ldap-port: 389
    ldap-search-bind-dn: CN=guacuser,CN=Users,{{ .Values.global.default_domain_ldap }}
    ldap-user-base-dn: CN=Users,{{ .Values.global.default_domain_ldap }}
    ldap-user-search-filter: (objectCategory=*)
    ldap-username-attribute: samAccountName
  secrets:
  	guacAdminPassword:
  	mysqlPassword:
  	mysqlRootPassword:
  sql:
  	enabled: true
  	version: latest
  	replicas: 1
  	mysqlUser: mysqluser
  	usersDatabase: guacdb
  	mysqlVolumeSize: 2G
  users:
  	enabled: true
  	version: latest
  	replicas: 1
  	debug: 'false'
  	manual_only: 'false'
  	auto_connection_dns: 'false'
  	auto_connection_dns_resolver: '192.168.1.159'
  	guac_admin_groups: 'GuacAdmin'
  	ldap_base_dn: '{{ .Values.global.default_domain_ldap }}'
  	ldap_computer_filter: '(objectCategory=Computer)'
  	ldap_group_name_from_conn_name_regex: '(.*?)\..+'
  	ldap_group_name_mod: '{regex}'
  	refresh_speed: '300'
  	manualConnections:
  	autoConnections: