kubernetes:
  storage: openebs-jiva-csi-default # use openebs-jiva-csi-default if using a multi-node cluster, obenebs-hostpath for single-node cluster.
  networking: MetalLB # use MetalLB for a multi-node cluster, NodePort for single-node cluster.
  metallb_ip: 192.168.1.156 # Used if netowrking is MetalLB
global:
  default_domain: 'domain.com'
  default_domain_ldap: 'DC=domain,DC=com'
  default_dns: 'guac.demo.example.com'
secrets:
  "mysql-secret":
    mysql_password: change_me
    mysql_root_password: change_me
    guacadmin_password: change_me
  "ldap-secret":
    ldap_password: change_me
  "duo-secret":
    duo_ad_password: change_me
    duo_api_hostname: change_me
    duo_integration_key: change_me
    duo_radius_secret: change_me
    duo_secret_key: change_me
  "route53":
    secret_access_key: change_me
  "smtp-relay":
    password: change_me
components:
  - haproxy
  - cert_manager
  - guacamole
  - guacamole_users
  - squid
  - dnsmasq
  - smtp
  - duo
mysql:
  version: latest
  mysql_database: guacamole
  mysql_username: guacamole
smtp:
  version: latest
  type: gmail # smarthost. if gmail, smarthost_* entries are not needed.
  gmail_user: demonotificationacct@gmail.com
  # smarthost_address: 1.2.3.4
  # smarthost_user: user@domain.com
  # smarthost_port: 587
  relay_networks: 0.0.0.0/0
cert_manager:
  # You must replace this email address with your own.
  # Let's Encrypt will use this to contact you about expiring
  # certificates, and issues related to your account.
  email: demonotificationacct@gmail.com
  route53_region: us-east-1
  route53_access_key_id: AKIAXCGVZA7GBFAPD2KE
  #route53_hosted_zone_id: Z0091177ZFZLS2BDDN6U
  server: https://acme-staging-v02.api.letsencrypt.org/directory #https://acme-v02.api.letsencrypt.org/directory
  dnsNames:
  - 'demo.example.com'
  - '*.demo.example.com'
duo:
  version: latest
  duo_ad_host: '{{ .Values.global.default_domain }}'
  duo_ad_user: 'DuoUser'
  duo_ad_search_dn: 'CN=Users,{{ .Values.global.default_domain_ldap }}'
  duo_failmode: 'secure'
dnsmasq:
  version: latest
  args:
    - '--server=192.168.1.159'
    - '--server=/domain.com/192.168.1.159'
squid:
  version: latest
  whitelists:
    rockwell.txt: |
      .rockwellautomation.custhelp.com
      .rockwellautomation.com
    symantic.txt: |
      liveupdate.symantec.com
      liveupdate.symantecliveupdate.com
      ent-shasta.rrs.symantec.com
      tses.broadcom.com
      telemetry.broadcom.com
      ent-shasta-mr-clean.symantec.com
      central.ss.crsi.symantec.com
      central.nrsi.symantec.com
      central.avsi.symantec.com
      central.b6.crsi.symantec.com
      central.crsi.symantec.com
      stnd-avpg.crsi.symantec.com
      avs-avpg.crsi.symantec.com
      stnd-ipsg.crsi.symantec.com
      bash-avpg.crsi.symantec.com
      sp.cwfservice.net
      tus1gwynwapex01.symantec.com
      faults.qalabs.symantec.com
      faults.symantec.com
      linux-repo.us.securitycloud.symantec.com
    windows_updates.txt: |
      asdf.windowsupdate.microsoft.com
      .update.microsoft.com
      .windowsupdate.com
      .download.windowsupdate.com
      download.microsoft.com
      wustat.windows.com
      ntservicepack.microsoft.com
      go.microsoft.com
      dl.delivery.mp.microsoft.com
  cfg: |
    #Set allowed ports
    acl SSL_ports port 443
    acl Safe_ports port 80          # http
    acl Safe_ports port 443         # https
    acl CONNECT method CONNECT

    # Block anything that is not ports 80/443
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports

    #Disable caching
    cache deny all

    #Support email for failure page.
    cache_mgr support@domain.local

    #Set source clients
    acl test_src src all

    #Set port number
    http_port 3128

    #Allow All
    http_access allow all
    http_access allow CONNECT all
guacamole:
  debug: false
  db_volume_size: 2G
  shared_volume_size: 12G
  version: 1.4.0
  properties: |
    enable-environment-properties: true
    ldap-encryption-method: none
    ldap-group-base-dn: {{ .Values.global.default_domain_ldap }}
    ldap-group-search-filter: (objectCategory=group)
    ldap-group-name-attribute: cn
    ldap-hostname: {{ .Values.global.default_domain }}
    ldap-port: 389
    ldap-search-bind-dn: CN=guacuser,CN=Users,{{ .Values.global.default_domain_ldap }}
    #ldap-search-bind-password: # set with env LDAP_SEARCH_BIND_PASSWORD
    ldap-user-base-dn: CN=Users,{{ .Values.global.default_domain_ldap }}
    ldap-user-search-filter: (objectCategory=*)
    ldap-username-attribute: samAccountName
guacamole_users:
  version: latest
  debug: 'true'
  auto_connection_dns: 'false'
  auto_connection_dns_resolver: '192.168.1.159'
  guac_admin_groups: 'GuacAdmin'
  ldap_base_dn: '{{ .Values.global.default_domain_ldap }}'
  ldap_computer_filter: '(objectCategory=Computer)'
  ldap_group_name_from_conn_name_regex: '(.*?)\..+'
  ldap_group_name_mod: '{regex}'
  refresh_speed: '300'
  manual_only: 'false'
  manual_connections: |
    manual_connections:
      defaults:
        connection:
          protocol: 'rdp'
        parameters:
          console-audio: 'true'
          create-drive-path: 'true'
          drive-name: 'shared'
          drive-path: '/shared'
          enable-drive: 'true'
          enable-printing: 'true'
          ignore-cert: 'true'
          port: '3389'
          printer-name: 'RemotePrinter'
          security: 'nla'
          username: '${GUAC_USERNAME}'
          password: '${GUAC_PASSWORD}'
          domain: '{{ .Values.global.default_domain }}'
      connections:
       - defaults: true
         connection:
           connection_name: 'TEST-CONNECTION.domain.com - 192.168.1.160'
         parameters:
           hostname: '192.168.1.160'
    #parameters section and specific paramters are only required if they are not the defaults.
    # If manual connections are specified, permissions are required to be set for all manual connections.
    # List all ldap groups under the connection_name for each manual connection. Any user in the ldap group
    # will have permission to connect with the specific connection.
    manual_permissions:
      "Domain Users":
        - 'TEST-CONNECTION.domain.com - 192.168.1.160'
      ThisIsATestGroup:
        - 'TEST-CONNECTION.domain.com - 192.168.1.160'
  auto_connections: |
    connection:
      protocol: 'rdp'
    parameters: # Connection parameters are defined here under 'Configuring Connections': https://guacamole.apache.org/doc/gug/configuring-guacamole.html
      console-audio: 'true'
      create-drive-path: 'true'
      drive-name: 'shared'
      drive-path: '/shared'
      enable-drive: 'true'
      enable-printing: 'true'
      ignore-cert: 'true'
      port: '3389'
      printer-name: 'RemotePrinter'
      security: 'nla'
      username: '${GUAC_USERNAME}'
      password: '${GUAC_PASSWORD}'
      domain: '{{ .Values.global.default_domain }}'
haproxy:
  ports:
    - name: http
#      protocol: TCP # default is TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443 # default is TCP
      targetPort: 8443
  version: 2.5.1
  cfg: |
    global
      log stdout format raw local0
      daemon
      # Default ciphers to use on SSL-enabled listening sockets.
      # For more information, see ciphers(1SSL).
      ssl-default-bind-ciphers kEECDH+aRSA+AES:kRSA+AES:+AES256:RC4-SHA:!kEDH:!LOW:!EXP:!MD5:!aNULL:!eNULL
      ssl-load-extra-del-ext

    defaults
      log     global
      mode    http
      option  httplog
      option  dontlognull
      timeout connect 10s
      timeout client 30s
      timeout server 30s

    frontend http
        bind *:8080
        mode http
        redirect scheme https code 301

    frontend https
        bind *:8443 ssl crt /usr/local/etc/certs/
        http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
        option forwardfor
        acl is_guac hdr(host) -i {{ .Values.global.default_dns }}
        use_backend guac if is_guac

    backend guac
        server guac guacamole-service:8080
